Fix the indentation error in quick_qc.py that causes errors generally.
Traceback (most recent call last):
  File "/FastSurfer/FastSurferCNN/run_prediction.py", line 34, in <module>
    from FastSurferCNN.quick_qc import check_volume
  File "/FastSurfer/FastSurferCNN/quick_qc.py", line 70
    sys.exit(0)
              ^
TabError: inconsistent use of tabs and spaces in indentation